# custom_cursor_colors = true
import = ["/Users/ashishnayan/.config/alacritty/colors/catppuccin-mocha.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
# TERM = "alacritty"
TERM =  "wezterm"

[font]
builtin_box_drawing = true
size = 18.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Medium"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Medium Italic"

[font.glyph_offset]
x = 0
y = 1

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Light Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Light"

[font.offset]
x = 1
y = 2

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "None"
opacity = 0.98
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[window.padding]
x = 4
y = 0
